# **Primeira aula de python**

In [ ]:
print("Olá, mundo!")

Olá, mundo!


In [ ]:
print('Olá')

Olá


# **Numpy**

In [ ]:
import time

start_time = time.time()
a = range(10000000)
b = range(10000000)
c = []

for i in range(len(a)):
  c.append(a[i] + b[i])

elapsed_time = time.time() - start_time
print(elapsed_time)

5.575728893280029


In [ ]:
import numpy as np

start_time = time.time()
a = np.arange(10000000)
b = np.arange(10000000)
c = []

c = a + b

elapsed_time = time.time() - start_time
print(elapsed_time)


0.20363545417785645


Criação de Arrays

In [ ]:
# Criar um array NumPy a partir de uma lista

lista = [1, 2, 3, 4, 5]
array_lista = np.array(lista)
print(f"Array criado a partir de uma lista: {array_lista}")

Array criado a partir de uma lista: [1 2 3 4 5]


In [ ]:
# Criar um array de zeros com forma especificada (3x4)
array_zeros = np.zeros((3,4))
print(array_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Criar um array de uns com forma especificada (2x2)
arrays_uns = np.ones((2,2))
print(arrays_uns)

[[1. 1.]
 [1. 1.]]


In [ ]:
# Criar um array com valores igualmente espaçados no intervalo de 0 a 9 (exclusivo)
array_arange = np.arange(9)
print(array_arange)

[0 1 2 3 4 5 6 7 8]


In [ ]:
# Criar um array com valores igualmente espaçados entre 0 e 1 com 5 elementos
array_linspace = np.linspace(0, 1, 5)
print(array_linspace)

[0.   0.25 0.5  0.75 1.  ]


Operações Matemáticas

In [ ]:
import numpy as np

In [ ]:
# Criando dois arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [ ]:
# Adição
soma = array1 + array2
print(f"Soma: {soma}")

Soma: [5 7 9]


In [ ]:
# Subtração
subtracao = array1 - array2
print(f"Subtração: {subtracao}")

Subtração: [-3 -3 -3]


In [ ]:
# Multiplicação
multiplicacao = array1 * array2
print(f"Multiplicação: {multiplicacao}")

Multiplicação: [ 4 10 18]


In [ ]:
# Divisão
divisao = array1 / array2
print(f"Divisão: {divisao}")

Divisão: [0.25 0.4  0.5 ]


In [ ]:
# Produto escalar
produto_escalar = np.dot(array1, array2)
print(f"Produto escalar: {produto_escalar}")

Produto escalar: 32


In [ ]:
# Matriz transposta
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz_transposta = np.transpose(matriz)
print("Matriz:")
print(matriz)
print("Matriz Transposta:")
print(matriz_transposta)

Matriz:
[[1 2 3]
 [4 5 6]]
Matriz Transposta:
[[1 4]
 [2 5]
 [3 6]]


Indexação e Fatiamento

In [ ]:
# Crie um array NumPy com valores de 10 a 19
arr = np.arange(10, 20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Acesse o elemento na posição 5 (índice 5)
elemento = arr[5]
print(elemento)

15


In [ ]:
# Fatiamento: Selecione um subconjunto do array
# Do índice 2 (inclusivo) ao índice 7 (exclusivo)
subconjunto = arr[2:7]
print(subconjunto)


[12 13 14 15 16]


In [ ]:
# Fatiamento: Selecione um subconjunto do array com incremento (com passo)
# Do índice 2 (inclusivo) ao índice 9 (exclusivo) com passo 2
subconjunto_passo = arr[2:9:2]
print(subconjunto_passo)

[12 14 16 18]


Funções Estatísticas

In [ ]:
# Crie um array NumPy com valores de 0 a 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Selecionando o menor valor
menor = np.min(arr)
index_menor = np.argmin(arr)
print(f'Menor valor: {menor} no índice: {index_menor}')

Menor valor: 0 no índice: 0


In [ ]:
# Selecionando o maior valor
maior = np.max(arr)
index_maior = np.argmax(arr)
print(f'Maior valor: {maior} no índice: {index_maior}')

Maior valor: 9 no índice: 9


In [ ]:
# Calculando a média
media = np.mean(arr)
print(f'Média: {media}')

Média: 4.5


In [ ]:
# Calculando a mediana
mediana = np.median(arr)
print(f"Mediana: {mediana}")

Mediana: 4.5


In [ ]:
# Calculando o desvio padrão
desvio_padrao = np.std(arr)
print(f"Desvio Padrão: {desvio_padrao}")

Desvio Padrão: 2.8722813232690143


In [ ]:
# Calculando a soma dos elementos
soma = np.sum(arr)
print(f"Soma: {soma}")

Soma: 45


Manipulação de Arrays

In [ ]:
# Crie um array NumPy com valores de 0 a 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Redimensionando o array para uma matriz 2x5
matriz = np.reshape(arr, (2, 5))
print(matriz)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# Criando outro array NumPy
arr2 = np.arange(10,20)
print(arr2)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Concatenando os dois arrays ao longo das linhas (eixo 0)
matriz_2 = np.reshape(arr2, (2, 5))
concatenado = np.concatenate((matriz, matriz_2), axis=0)
print(concatenado)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# Concatenando os dois arrays ao longo das colunas (eixo 1)
matriz_2 = np.reshape(arr2, (2, 5))
concatenado = np.concatenate((matriz, matriz_2), axis=1)
print(concatenado)

[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


In [ ]:
# Crie um array NumPy com valores de 0 a 9
arr = np.arange(10)

# Dividindo o array em três partes de tamanhos desiguais
partes = np.array_split(arr, 3)
partes_concatenadas = np.concatenate(partes)
print(partes)
print(partes_concatenadas)


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


Gerador de Números Aleatórios

In [ ]:
# Gerando 5 números aleatórios entre 0 e 1
random_numbers = np.random.rand(5)
print(random_numbers)

[0.75554471 0.95687861 0.66698889 0.48166776 0.72945328]


In [ ]:
# Gerando 5 números aleatórios em uma distribuição normal (gaussiana)
random_numbers = np.random.randn(5)
print(random_numbers)

[ 0.1090675  -0.52269377  0.21475931  0.95183146  0.42846032]


In [ ]:
# Gerando 5 números inteiros aleatórios entre 1 e 10
random_numbers = np.random.randint(1, 11, 5)
print(random_numbers)

[ 9  8  7 10  9]


In [ ]:
# Gerando uma matriz (3, 4) com números inteiros aleatórios entre 1 e 10

random_numbers = np.random.randint(1, 11, (3, 4))
print(random_numbers)

[[ 4  4  6  6]
 [ 9  9  4  9]
 [ 5  6  9 10]]


In [ ]:
# Gerando números inteiros aleatórios entre 10 e 40 (uniforme) com duas casas decimais

random_numbers = np.random.uniform(10, 40, 30)
random_numbers = np.round(random_numbers, 2)
print(random_numbers)

[10.21 37.3  38.27 24.3  21.27 31.64 31.41 15.52 31.87 29.37 25.05 31.91
 30.89 18.89 12.09 33.12 23.24 29.39 30.34 21.57 39.46 13.02 24.36 24.56
 38.15 26.27 21.14 38.03 11.08 20.62]


Álgebra Linear

In [ ]:
# Calcular as diferenças discretas entre elementos consecutivos em um array.
arr = np.array([2, 4, 7, 11, 16])
differences = np.diff(arr)
print(differences)

[2 3 4 5]


In [ ]:
# Definindo uma matriz
matriz = np.array([[2, 3], [1, 4]])

# Calculando a matriz inversa
matriz_inversa = np.linalg.inv(matriz)

print(matriz)
print(matriz_inversa)

[[2 3]
 [1 4]]
[[ 0.8 -0.6]
 [-0.2  0.4]]


In [ ]:
# Calculando o determinante
determinante = np.linalg.det(matriz)

print(matriz)
print(determinante)

[[2 3]
 [1 4]]
5.000000000000001


Funções de Comparação

In [ ]:
# Exemplo Básico

# Criar um array NumPy
arr = np.array([1, 2, 3, 4, 5, 6])

# Usar np.where() para obter os índices que atendem à condição
resultado = np.where(arr > 3)

print(resultado)



(array([3, 4, 5]),)


In [ ]:
# Exemplo de substituição

arr = np.array([1, 2, 3, 4, 5, 6])

# Usar np.where() para substituir valores com base em uma condição
new_arr = np.where(arr < 3, -1, arr)
print(new_arr)

[-1 -1  3  4  5  6]


In [ ]:
# Exemplo com condições múltiplas
arr = np.array([1, 2, 3, 4, 5, 6])

# Usar np.where() com condições múltiplas
new_arr = np.where(arr < 3, -1, np.where(arr > 4, 10, arr)) #np.where(condição_1, valor_se_verdadeiro_1, np.where(condição_2, valor_se_verdadeiro_2, valor_se_falso))
print(new_arr)

[-1 -1  3  4 10 10]


Seleção e Filtragem

In [ ]:
# Criando um array de exemplo
arr = np.arange(1, 11)

# Selecionando apenas os elementos maiores que 5
selecionados = arr[arr > 5]
print(selecionados)

[ 6  7  8  9 10]


In [ ]:
# Filtrando elementos pares
filtrados = arr[arr % 2 == 0]
print(filtrados)

[ 2  4  6  8 10]


In [ ]:
# Selecionando elementos dentro de um intervalo
intervalo = arr[(arr >= 3) & (arr <= 7)]
print(intervalo)

[3 4 5 6 7]


Exercícios

1.   Import Numpy como np
2.   Crie uma array de 10 zeros
3.   Crie um array de inteiros de 10 até 50
4.   Crie um array dos números pares de 10 até 50
5.   Criei uma matriz 3x3 com valores variando de 0 até 8
6.   Crie uma matriz identidade 3x3
7.   Use NumPy para gerar números aleatórios entre 0 e 1
8.   Inserir 5 números inteiros em um array a partir do input()

In [ ]:
import numpy as np

In [ ]:
array_zeros = np.zeros(10)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array_inteiros = np.arange(10, 51)
print(array_inteiros)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
array_inteiros = np.arange(10, 51, 2)
print(array_inteiros)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
matriz_3_3 = np.arange(9).reshape(3, 3)
print(matriz_3_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
matriz_identidade = np.eye(3)
print(matriz_identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
numeros_aleatorios = np.random.rand(5, 5)
print(numeros_aleatorios)

[[0.0894838  0.76440891 0.32614867 0.94576953 0.26938573]
 [0.30432336 0.82090419 0.0580252  0.32615654 0.77581212]
 [0.95035084 0.9174656  0.12935745 0.9200291  0.80432215]
 [0.9014307  0.08429448 0.62488088 0.62855312 0.6264153 ]
 [0.98074232 0.80237245 0.71884584 0.93543597 0.43503074]]


In [ ]:
random_numbers = np.random.rand(1, 11, 5)

In [ ]:
lista = []
for i in range(5):
  lista.append(int(input("Digite um número: ")))

arr = np.array(lista)

Digite um número: 1
Digite um número: 2
Digite um número: 3
Digite um número: 4
Digite um número: 5


In [ ]:
arr = np.array([int(input("Digite um número: ")) for i in range(5)])

Digite um número: 1
Digite um número: 2
Digite um número: 3
Digite um número: 4
Digite um número: 5
