# Lista de Exercício 01 - Numpy

Nome dos integrantes do grupo: John Wesley, Heraldo Almeida, Ivo de Sousa

Questão 01. Você é um pesquisador de clima e deseja registrar as temperaturas diárias de uma cidade. Peça ao usuário para inserir as temperaturas de 7 dias consecutivos e, em seguida, exiba a temperatura média, a temperatura máxima, mínima, o dia em que a temperatura foi mais baixa e o dia que a temperatura foi mais alta.

In [ ]:
import numpy as np

In [ ]:


dias = np.array([float(input("Insira a temperatura do dia: ")) for i in range(7)])

print(f"Temperatura média: {np.mean(dias)}")
print(f"Temperatura máxima: {np.max(dias)}")
print(f"Temperatura mínima: {np.min(dias)}")
print(f"Dia Temperatura máxima: {np.argmax(dias) + 1}")
print(f"Dia Temperatura mínima: {np.argmin(dias) + 1}")


Insira a temperatura do dia: 20
Insira a temperatura do dia: 14
Insira a temperatura do dia: 33
Insira a temperatura do dia: 21
Insira a temperatura do dia: 45
Insira a temperatura do dia: 22
Insira a temperatura do dia: 16
Temperatura média: 24.428571428571427
Temperatura máxima: 45.0
Temperatura mínima: 14.0
Dia Temperatura máxima: 5
Dia Temperatura mínima: 2


Questão 02. Você está trabalhando em um projeto de engenharia e deseja calcular a força resultante de várias forças. Solicite ao usuário para inserir os valores de 5 forças e, em seguida, calcule e exiba a força resultante (soma das forças).

In [ ]:
forca_resultante = np.array([float(input("Insira o valor da força: ")) for i in range(5)])

print(f"Força resultante: {np.sum(forca_resultante)}")

Insira o valor da força: 1
Insira o valor da força: 2
Insira o valor da força: 3
Insira o valor da força: 4
Insira o valor da força: 5
Força resultante: 15.0


Questão 03. Você está trabalhando com um sistema de mapeamento e precisa realizar operações de indexação e fatiamento em um mapa representado por uma matriz. O mapa possui números inteiros aleatórios, e você precisa acessar os valores em posições específicas.

1.   Crie uma matriz bidimensional (um mapa) com números inteiros aleatórios entre 1 e 100. Peça ao usuário para inserir o número de linhas e colunas para o mapa.
2.   Solicite ao usuário que escolha uma linha e uma coluna no mapa.
3.   Exiba o valor encontrado na posição escolhida.

In [ ]:
#Pede ao usuário o números e linhas e de colunas:
linhas = int(input("Insira quantas linhas terão o mapa:"))
colunas = int(input("Insira quantas colunas terão o mapa:"))

#Gera uma matriz com numeros inteiros aleatorios de 0 a 100 e o numero de linhas e colunas é definido pelo usuário
mapa = np.random.randint(1, 100, (linhas, colunas))
print(f"Mapa:\n{mapa}")

#Solicita uma linha e uma coluna
encontrar_linha = int(input("Insira a linha desejada: "))
encontrar_coluna = int(input("Insira a coluna desejada: "))

#armazena em uma váriavel o valor encontrado e em seguinda exibe na tela
print(f"Valor na posição ({encontrar_linha}, {encontrar_coluna})mapa: {mapa[encontrar_linha - 1][encontrar_coluna - 1]}")


Insira quantas linhas terão o mapa:10
Insira quantas colunas terão o mapa:10
Mapa:
[[61 35 33 47 72 65 96 66 53 25]
 [85 89 69 39 54 73 13 26 70 45]
 [86 24 21 23 53 16 59 44 40 77]
 [78 16 97  4 47 56 15 62  1 98]
 [48 85  8 69 49 80 53 98 25 54]
 [50 15 61 15 53 97 22 85 91 92]
 [16 27 60 15 39 24 46 60 66 80]
 [68 20 13 93 28 56 58 87 59 45]
 [95 60 55 52 71 93 65 86 91 79]
 [43 97 98 72 19 82 36 22 88 15]]
Insira a linha desejada: 5
Insira a coluna desejada: 2
Valor na posição (5, 2)mapa: 85


4Questão 04. Você está trabalhando em um projeto de pesquisa de mercado e deseja calcular as estatísticas de idade de um grupo de pessoas. Peça ao usuário para inserir as idades de 10 pessoas e, em seguida, calcule e exiba a média, a mediana e o desvio padrão das idades.

In [ ]:
idades = np.array([float(input("Insira a idade: ")) for i in range(10)])

print(f"Média das idades: {np.mean(idades)}")
print(f"Mediana das idades: {np.median(idades)}")
print(f"Desvio padrão das idades: {np.std(idades)}")

Insira a idade: 10
Insira a idade: 20
Insira a idade: 30
Insira a idade: 40
Insira a idade: 50
Insira a idade: 60
Insira a idade: 70
Insira a idade: 80
Insira a idade: 90
Insira a idade: 100
Média das idades: 55.0
Mediana das idades: 55.0
Desvio padrão das idades: 28.722813232690143


Questão 05. Você está construindo um simulador de lançamento de dados e deseja gerar números aleatórios. Peça ao usuário para inserir o número de vezes que deseja lançar um dado de 6 faces. Em seguida, gere e exiba um vetor NumPy com os resultados desses lançamentos.

In [ ]:
vezes_jogadas = int(input("Insira o número de lançamentos: "))
lista_lancamentos = np.random.randint(1, 6, vezes_jogadas)
print(f"Resultados dos lançamentos: {lista_lancamentos}")

Insira o número de lançamentos: 10
Resultados dos lançamentos: [1 1 2 5 2 3 2 4 5 3]


Questão 06. Você é um fotógrafo digital e está trabalhando em um projeto de processamento de imagens. Crie um array NumPy que represente uma imagem em escala de cinza com valores aleatórios. Normalize a imagem dividindo todos os valores pelo valor máximo possível (255). Exiba a imagem original e a imagem normalizada.

In [ ]:
linhas = int(input("Digite o número de linhas da imagem: "))
colunas = int(input("Digite o número de colunas da imagem: "))


imagem_escala_cinza = np.random.randint(0, 255, (linhas,colunas))
print(f"Imagem original:\n{imagem_escala_cinza}\n")

imagem_normalizada = imagem_escala_cinza / 255
print(f"Imagem normalizada:\n{imagem_normalizada}")


Digite o número de linhas da imagem: 10
Digite o número de colunas da imagem: 10
Imagem original:
[[ 40 252   2  32 233 129 190 213 152 137]
 [ 11  64 232  86 201 181 167 241  14 225]
 [ 89 234 226 196  52 237 103  80 165  30]
 [235 109 168 146  58 198 146  72 160  22]
 [247 120 103 158 172 171  86 144 234 207]
 [234 168  90 184  81  76 246   0  81 154]
 [130 145 106 128 245  79   8 170  11  20]
 [119  54  53 151 158  43  56 251  87 205]
 [ 46  96 147 219 244 161  27 124  38 208]
 [ 21 186 218  30 129 246  74  13  32 129]]

Imagem normalizada:
[[0.15686275 0.98823529 0.00784314 0.1254902  0.91372549 0.50588235
  0.74509804 0.83529412 0.59607843 0.5372549 ]
 [0.04313725 0.25098039 0.90980392 0.3372549  0.78823529 0.70980392
  0.65490196 0.94509804 0.05490196 0.88235294]
 [0.34901961 0.91764706 0.88627451 0.76862745 0.20392157 0.92941176
  0.40392157 0.31372549 0.64705882 0.11764706]
 [0.92156863 0.42745098 0.65882353 0.57254902 0.22745098 0.77647059
  0.57254902 0.28235294 0.62745098 0.

11Questão 07. Neste exercício, você atua como um analista financeiro que lida com dados de investimentos. Considere o preço de fechamento diário de ações de uma empresa ao longo de uma semana. Crie um programa que execute as seguintes operações:

Solicite ao usuário que insira os preços de fechamento diários da ação da empresa durante uma semana (7 dias). Armazene esses preços em um array NumPy.

1. Calcule o retorno diário da ação, que é a diferença entre o preço de fechamento atual e o preço de fechamento do dia anterior.
2. Calcule o retorno médio diário da ação.
3. Calcule o desvio padrão dos retornos diários, que é uma medida de volatilidade.

In [ ]:
preco_fechamento = np.array([float(input(f"Digite o preço de fechamento do dia {i+1}: ")) for i in range(7)])
retorno_diario = []

for i in range(7):
  if i == 0:
    retorno_diario.append(preco_fechamento[i])
  else:
    retorno_diario.append(preco_fechamento[i] - preco_fechamento[i-1])

retorno_diario = np.array(retorno_diario)

print(f"Retorno médio diário: {np.mean(retorno_diario)}")
print(f"Desvio padrão dos retornos diários: {np.std(retorno_diario)}")

Digite o preço de fechamento do dia 1: 10
Digite o preço de fechamento do dia 2: 20
Digite o preço de fechamento do dia 3: 30
Digite o preço de fechamento do dia 4: 40
Digite o preço de fechamento do dia 5: 50
Digite o preço de fechamento do dia 6: 60
Digite o preço de fechamento do dia 7: 70
Retorno médio diário: 10.0
Desvio padrão dos retornos diários: 0.0


Questão 08. Você é responsável pelo controle de estoque de uma loja e deseja identificar quais produtos estão em baixo estoque. Crie um programa que permita ao usuário inserir o nome e a quantidade em estoque de vários produtos. Após inserir os dados de todos os produtos, o programa deverá usar o NumPy para identificar e exibir uma lista dos produtos que têm menos de uma quantidade específica em estoque.

Instruções:

1. Solicite ao usuário quantos produtos deseja inserir.
2. Solicite a quantidade mínima em estoque que define o limite de "baixo estoque".
3. Para cada produto, solicite o nome e a quantidade em estoque.
4. Após inserir todos os produtos, use o NumPy para identificar os produtos que têm uma quantidade em estoque inferior à quantidade mínima especificada.

In [ ]:
nme_produto = ""
qtd_estoque = 0
estoque = {}

qtd_produtos = int(input("Quantos produtos deseja inserir? "))
alerta_estoque = int(input("Qual é a quantidade mínima para considerar baixo estoque? "))

for i in range(qtd_produtos):
  nme_produto = input("Digite o nome do produto: ")
  qtd_estoque = int(input(f"Digite a quantidade em estoque para {nme_produto}: "))

  estoque[nme_produto] = {"estoque":qtd_estoque}

#Array com o nome dos produtos
protudos_alerta = np.array([(i) for i in estoque])

#Array com o valor de estoque de cada produto
baixo_estoque = np.array([(estoque[i]['estoque']) for i in estoque])

#Filtrando apenas os produtos que possuem estoque abaixo da quantidade de alerta
baixo_estoque = np.where(baixo_estoque < alerta_estoque)

#Exibindo o nome dos produtos filtrados em alerta
print(f"Produtos em baixo estoque (menos de {alerta_estoque} unidades): ")
for i in range(len(baixo_estoque[0])):
  print(protudos_alerta[baixo_estoque[0][i]])

Quantos produtos deseja inserir? 3
Qual é a quantidade mínima para considerar baixo estoque? 5
Digite o nome do produto: armário
Digite a quantidade em estoque para armário: 2
Digite o nome do produto: cadeira
Digite a quantidade em estoque para cadeira: 10
Digite o nome do produto: mesa
Digite a quantidade em estoque para mesa: 5
Produtos em baixo estoque (menos de 5 unidades): 
armário
